// <auto-generated />
namespace Hospital.SaoJose.Negocios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProfissionalSaude : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfissionalSaude));
        
        string IMigrationMetadata.Id
        {
            get { return "201607091430393_ProfissionalSaude"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
